// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyASKZsNel_e1xnUHKAKLczHIQDLAUnlF9k',
    appId: '1:580775335998:web:84855e5f5b67be507d196f',
    messagingSenderId: '580775335998',
    projectId: 'fir-flutter-codelab-90e4b',
    authDomain: 'fir-flutter-codelab-90e4b.firebaseapp.com',
    storageBucket: 'fir-flutter-codelab-90e4b.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAykZ83eGzjA-F-8ADzGc1CHip1z7vkITA',
    appId: '1:580775335998:android:85b3838cda78c3657d196f',
    messagingSenderId: '580775335998',
    projectId: 'fir-flutter-codelab-90e4b',
    storageBucket: 'fir-flutter-codelab-90e4b.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCpsNhJS56i3Xue1Xl1RU-V2aDxjmPTJ30',
    appId: '1:580775335998:ios:834e89b1554a66f27d196f',
    messagingSenderId: '580775335998',
    projectId: 'fir-flutter-codelab-90e4b',
    storageBucket: 'fir-flutter-codelab-90e4b.firebasestorage.app',
    iosBundleId: 'com.example.gtkFlutter',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCpsNhJS56i3Xue1Xl1RU-V2aDxjmPTJ30',
    appId: '1:580775335998:ios:834e89b1554a66f27d196f',
    messagingSenderId: '580775335998',
    projectId: 'fir-flutter-codelab-90e4b',
    storageBucket: 'fir-flutter-codelab-90e4b.firebasestorage.app',
    iosBundleId: 'com.example.gtkFlutter',
  );
}
